### PR TITLE
Procurement resource

### PR DESCRIPTION
**Pull request by tsherlockcraig**
This is now I think 99% complete. Ready for review, some final adjustments, and then merge once the co-authors formally accept it. I'm out next week, but if you ask for a vote, @safrazier17 , then I vote 'yes' :)

known issues
- there's bolded text under resources near the top where we still need a link (or the deletion of that text)

items i'd suggest reviewing specifically:
- I'm not totally sure I handled either the 'table of contents' or the headers correctly. Specifically, I didn't include each software application in the TOC, and I left them as h2s rather than h1s in the body, because it felt like they needed to be "under" the "system requirements" header. this feels like the right organization, but i'm hesitant about not making key words like "scheduling system" sufficiently obvious.
- I adapted the intro text to "system requirements"

### CODE REVIEW

**Comment by tsherlockcraig** [comment]
if you'd like to adjust the images at all, they're downloaded from the google draw files here: https://drive.google.com/drive/folders/11_A508WCLosAD7I-TLKUvoDGNKD5rI5V?usp=sharing (which I've given Scott and Elizabeth editing access to)

**Comment by e-lo** [comment]
Added top-level nav: 
image

**Review by thekaveman — APPROVED** [review]
I applied some small formatting cleanups to make the linter happy.

I also removed the manual Table of Contents from the new Procurement page, each page gets an auto-TOC from the heading levels.

In https://github.com/interoperable-mobility/principles/pull/15#pullrequestreview-1543775112 I added a small fix to incorporate the TOC into the left-side menu rather than making folks scan all the way to the right-side, which should be a better experience.

**Comment by thekaveman** [comment]
@safrazier17 fixed merge conflicts

**Comment by tsherlockcraig** [comment]
@safrazier17 sorry I just noticed that I left in one bit of 'comment' text near the top of the document. Under Resources: "The case for interoperability, link needed" --> ', link needed' should be deleted and the previous text should be a hyperlink, but this was a resource that per the Google doc I don't have. Could you either add that link or delete this bullet?

**Comment by safrazier17** [comment]
Not a problem, deleted the placeholder text. If we determine what that
resource is referring to then we can add it back in. But i'm still unclear
on that

**Pull request merged**
